// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_codes.sql

package sqldb

import (
	"context"
	"time"
)

const createMagicCode = `-- name: CreateMagicCode :exec
INSERT INTO magic_codes (
    id,
    email,
    code_hash,
    expires_at,
    attempts,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    0,
    ?5
)
`

type CreateMagicCodeParams struct {
	ID        string
	Email     string
	CodeHash  string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateMagicCode(ctx context.Context, arg CreateMagicCodeParams) error {
	_, err := q.db.ExecContext(ctx, createMagicCode,
		arg.ID,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredMagicCodes = `-- name: DeleteExpiredMagicCodes :execrows
DELETE FROM magic_codes
WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredMagicCodes(ctx context.Context, expiresBefore time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredMagicCodes, expiresBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestUnusedMagicCodeByEmail = `-- name: GetLatestUnusedMagicCodeByEmail :one
SELECT id, email, code_hash, expires_at, used_at, attempts, created_at
FROM magic_codes
WHERE email = ?1
  AND used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestUnusedMagicCodeByEmail(ctx context.Context, email string) (MagicCode, error) {
	row := q.db.QueryRowContext(ctx, getLatestUnusedMagicCodeByEmail, email)
	var i MagicCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const incrementMagicCodeAttempts = `-- name: IncrementMagicCodeAttempts :one
UPDATE magic_codes
SET attempts = attempts + 1
WHERE id = ?1
  AND attempts < ?2
RETURNING attempts
`

type IncrementMagicCodeAttemptsParams struct {
	ID          string
	MaxAttempts int64
}

func (q *Queries) IncrementMagicCodeAttempts(ctx context.Context, arg IncrementMagicCodeAttemptsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, incrementMagicCodeAttempts, arg.ID, arg.MaxAttempts)
	var attempts int64
	err := row.Scan(&attempts)
	return attempts, err
}

const markMagicCodeUsedIfUnused = `-- name: MarkMagicCodeUsedIfUnused :execrows
UPDATE magic_codes
SET used_at = ?1
WHERE id = ?2
  AND used_at IS NULL
`

type MarkMagicCodeUsedIfUnusedParams struct {
	UsedAt *time.Time
	ID     string
}

func (q *Queries) MarkMagicCodeUsedIfUnused(ctx context.Context, arg MarkMagicCodeUsedIfUnusedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markMagicCodeUsedIfUnused, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
