// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"time"
)

type MagicCode struct {
	ID        string
	Email     string
	CodeHash  string
	ExpiresAt time.Time
	UsedAt    *time.Time
	Attempts  int64
	CreatedAt time.Time
}

type Message struct {
	ID        string
	AuthorID  string
	Content   string
	CreatedAt time.Time
	EditedAt  *time.Time
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt *time.Time
}

type RegistrationToken struct {
	ID        string
	Email     string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type User struct {
	ID             string
	Username       string
	Email          string
	AvatarUrl      *string
	SessionVersion int64
	CreatedAt      time.Time
	UpdatedAt      *time.Time
	DeactivatedAt  *time.Time
}
