// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"time"
)

type Blob struct {
	ID                 string
	Kind               string
	UploadedBy         string
	StoragePath        string
	MimeType           string
	SizeBytes          int64
	OriginalName       string
	MessageID          *string
	ClaimedAt          *time.Time
	ExpiresAt          *time.Time
	PreviewStoragePath *string
	PreviewMimeType    *string
	PreviewSizeBytes   *int64
	PreviewWidth       *int64
	PreviewHeight      *int64
	CreatedAt          time.Time
}

type MagicCode struct {
	ID        string
	Email     string
	CodeHash  string
	ExpiresAt time.Time
	UsedAt    *time.Time
	Attempts  int64
	CreatedAt time.Time
}

type Message struct {
	ID        string
	AuthorID  string
	Content   string
	CreatedAt time.Time
	EditedAt  *time.Time
}

type RefreshToken struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt *time.Time
}

type RegistrationToken struct {
	ID        string
	Email     string
	TokenHash string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type ServerSetting struct {
	ID         int64
	IconBlobID *string
	UpdatedAt  time.Time
}

type User struct {
	ID             string
	Username       string
	Email          string
	AvatarUrl      *string
	SessionVersion int64
	CreatedAt      time.Time
	UpdatedAt      *time.Time
	DeactivatedAt  *time.Time
}
