// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package sqldb

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (
    id,
    user_id,
    token_hash,
    expires_at,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type CreateRefreshTokenParams struct {
	ID        string
	UserID    string
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens
WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresBefore time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens, expiresBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at, revoked_at
FROM refresh_tokens
WHERE token_hash = ?1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE refresh_tokens
SET revoked_at = ?1
WHERE user_id = ?2
  AND revoked_at IS NULL
`

type RevokeAllRefreshTokensForUserParams struct {
	RevokedAt *time.Time
	UserID    string
}

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, arg RevokeAllRefreshTokensForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllRefreshTokensForUser, arg.RevokedAt, arg.UserID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :execrows
UPDATE refresh_tokens
SET revoked_at = ?1
WHERE id = ?2
  AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	RevokedAt *time.Time
	ID        string
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshToken, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeRefreshTokenForRotation = `-- name: RevokeRefreshTokenForRotation :execrows
UPDATE refresh_tokens
SET revoked_at = ?1
WHERE id = ?2
  AND revoked_at IS NULL
  AND expires_at > ?3
`

type RevokeRefreshTokenForRotationParams struct {
	RevokedAt *time.Time
	ID        string
	Now       time.Time
}

func (q *Queries) RevokeRefreshTokenForRotation(ctx context.Context, arg RevokeRefreshTokenForRotationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeRefreshTokenForRotation, arg.RevokedAt, arg.ID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
