// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registration_tokens.sql

package sqldb

import (
	"context"
	"time"
)

const consumeValidRegistrationToken = `-- name: ConsumeValidRegistrationToken :one
UPDATE registration_tokens
SET used_at = ?1
WHERE token_hash = ?2
  AND used_at IS NULL
  AND expires_at > ?3
RETURNING id, email, token_hash, expires_at, used_at, created_at
`

type ConsumeValidRegistrationTokenParams struct {
	UsedAt    *time.Time
	TokenHash string
	Now       time.Time
}

func (q *Queries) ConsumeValidRegistrationToken(ctx context.Context, arg ConsumeValidRegistrationTokenParams) (RegistrationToken, error) {
	row := q.db.QueryRowContext(ctx, consumeValidRegistrationToken, arg.UsedAt, arg.TokenHash, arg.Now)
	var i RegistrationToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRegistrationToken = `-- name: CreateRegistrationToken :exec
INSERT INTO registration_tokens (
    id,
    email,
    token_hash,
    expires_at,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type CreateRegistrationTokenParams struct {
	ID        string
	Email     string
	TokenHash string
	ExpiresAt time.Time
	CreatedAt time.Time
}

func (q *Queries) CreateRegistrationToken(ctx context.Context, arg CreateRegistrationTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRegistrationToken,
		arg.ID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredRegistrationTokens = `-- name: DeleteExpiredRegistrationTokens :execrows
DELETE FROM registration_tokens
WHERE expires_at < ?1
`

func (q *Queries) DeleteExpiredRegistrationTokens(ctx context.Context, expiresBefore time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredRegistrationTokens, expiresBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getValidRegistrationToken = `-- name: GetValidRegistrationToken :one
SELECT id, email, token_hash, expires_at, used_at, created_at
FROM registration_tokens
WHERE token_hash = ?1
  AND used_at IS NULL
  AND expires_at > ?2
LIMIT 1
`

type GetValidRegistrationTokenParams struct {
	TokenHash string
	Now       time.Time
}

func (q *Queries) GetValidRegistrationToken(ctx context.Context, arg GetValidRegistrationTokenParams) (RegistrationToken, error) {
	row := q.db.QueryRowContext(ctx, getValidRegistrationToken, arg.TokenHash, arg.Now)
	var i RegistrationToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
