// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server_settings.sql

package sqldb

import (
	"context"
	"time"
)

const getServerSettings = `-- name: GetServerSettings :one
SELECT id, icon_blob_id, updated_at
FROM server_settings
WHERE id = 1
LIMIT 1
`

func (q *Queries) GetServerSettings(ctx context.Context) (ServerSetting, error) {
	row := q.db.QueryRowContext(ctx, getServerSettings)
	var i ServerSetting
	err := row.Scan(&i.ID, &i.IconBlobID, &i.UpdatedAt)
	return i, err
}

const setServerIconBlobID = `-- name: SetServerIconBlobID :execrows
UPDATE server_settings
SET icon_blob_id = ?1,
    updated_at = ?2
WHERE id = 1
`

type SetServerIconBlobIDParams struct {
	IconBlobID *string
	UpdatedAt  time.Time
}

func (q *Queries) SetServerIconBlobID(ctx context.Context, arg SetServerIconBlobIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setServerIconBlobID, arg.IconBlobID, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
