// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqldb

import (
	"context"
	"time"
)

const countUsersByUsername = `-- name: CountUsersByUsername :one
SELECT COUNT(*)
FROM users
WHERE username = ?1
`

func (q *Queries) CountUsersByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    username,
    email,
    session_version,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    1,
    ?4
)
`

type CreateUserParams struct {
	ID        string
	Username  string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.CreatedAt,
	)
	return err
}

const deactivateUser = `-- name: DeactivateUser :execrows
UPDATE users
SET deactivated_at = ?1,
    updated_at = ?2
WHERE id = ?3
  AND deactivated_at IS NULL
`

type DeactivateUserParams struct {
	DeactivatedAt *time.Time
	UpdatedAt     *time.Time
	ID            string
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deactivateUser, arg.DeactivatedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveUserByID = `-- name: GetActiveUserByID :one
SELECT id, username, email, avatar_url, session_version, created_at, updated_at, deactivated_at
FROM users
WHERE id = ?1
  AND deactivated_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.SessionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, avatar_url, session_version, created_at, updated_at, deactivated_at
FROM users
WHERE email = ?1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.AvatarUrl,
		&i.SessionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const incrementUserSessionVersion = `-- name: IncrementUserSessionVersion :execrows
UPDATE users
SET session_version = session_version + 1,
    updated_at = ?1
WHERE id = ?2
`

type IncrementUserSessionVersionParams struct {
	UpdatedAt *time.Time
	ID        string
}

func (q *Queries) IncrementUserSessionVersion(ctx context.Context, arg IncrementUserSessionVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementUserSessionVersion, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, username, avatar_url, created_at, updated_at
FROM users
WHERE deactivated_at IS NULL
ORDER BY username
`

type ListActiveUsersRow struct {
	ID        string
	Username  string
	AvatarUrl *string
	CreatedAt time.Time
	UpdatedAt *time.Time
}

func (q *Queries) ListActiveUsers(ctx context.Context) ([]ListActiveUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUsersRow{}
	for rows.Next() {
		var i ListActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateUser = `-- name: ReactivateUser :execrows
UPDATE users
SET deactivated_at = NULL,
    updated_at = ?1
WHERE id = ?2
  AND deactivated_at IS NOT NULL
`

type ReactivateUserParams struct {
	UpdatedAt *time.Time
	ID        string
}

func (q *Queries) ReactivateUser(ctx context.Context, arg ReactivateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reactivateUser, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUsername = `-- name: UpdateUsername :execrows
UPDATE users
SET username = ?1,
    updated_at = ?2
WHERE id = ?3
`

type UpdateUsernameParams struct {
	Username  string
	UpdatedAt *time.Time
	ID        string
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUsername, arg.Username, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
